name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Format code with Black
      run: black pioneer-uploader.py

    - name: Build with PyInstaller
      run: pyinstaller --onefile pioneer-uploader.py

    - name: Publish artifact
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v2
      with:
        name: publish-artifact
        path: dist
    
    - name: Run tests
      run: pytest
