name: Tox Testing

on: 
  push:
    branches-ignore:
      - 'dependabot**'

jobs:
  tox:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: tox
    
    - name: Publish artifact
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: pioneer-uploader
        path: ./dist
        if-no-files-found: error
